#pragma once
#include "NativeGameplayTags.h"


namespace SharedGameplayTag
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Health)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_MaxHealth)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Rage)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_PrimaryAttack)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_SecondaryAttack)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_SpecialAttack)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_Sprint)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StatusEffect_Sprinting)
}
